### ISSUE TITLE
Custom sql scripts fail to execute on bootstrap startup

### ISSUE THREAD

**Issue by tommyalatalo** [bitnami/bitnami-docker-mariadb-galera#23]
When putting sql files into /docker-entrypoint-initdb.d they fail to execute because the database is not actually running yet.
Image used is `bitnami/mariadb-galera:10.5.5`, docker version 19.03.8, build afacb8b7f0

1. Mount a .sql file into /docker-entrypoint-initdb.d/myscript.sql
2. Start the bootstrap container
3. The container crashes with message `ERROR 2002 (HY000): Can't connect to local MySQL server through
socket '/var/run/mysqld/mysqld.sock' (111)`

Expected behavior would be to start up the bootstrap node and once the socket is up the sql files would be executed.
Looking at the last sections setup.sh below, it appears the DB should be initialized and running when the sql files are executed, but that seems to not be the case when starting the container.

```
# Ensure MariaDB is initialized
mysql_initialize
# Ensure LDAP is initialized
is_boolean_yes "$DB_ENABLE_LDAP" && ldap_initialize
# Allow running custom initialization scripts
mysql_custom_init_scripts <-- why is socket not listening here?
# Stop MariaDB before flagging it as fully initialized.
# Relying only on the trap defined above could produce a race condition.
mysql_stop
```

**Comment by miguelaeh** [comment]
Hi @tommyalatalo ,
I am not able to reproduce the issue.
I just cloned the repository, created a custom sql file and added the volume to the docker-compose obtaining the expected output:
```
mariadb-galera_1  | mariadb 06:15:52.57 INFO  ==> Initializing mariadb database
mariadb-galera_1  | mariadb 06:15:52.58 INFO  ==> Updating 'my.cnf' with custom configuration
mariadb-galera_1  | mariadb 06:15:52.61 INFO  ==> Setting wsrep_node_name option
mariadb-galera_1  | mariadb 06:15:52.62 INFO  ==> Setting wsrep_node_address option
mariadb-galera_1  | mariadb 06:15:54.46 INFO  ==> Starting mariadb in background
mariadb-galera_1  | mariadb 06:15:56.59 INFO  ==> Loading user's custom files from /docker-entrypoint-initdb.d
mariadb-galera_1  | mariadb 06:15:56.62 INFO  ==> Stopping mariadb
mariadb-galera_1  | mariadb 06:15:58.62 INFO  ==> ** MariaDB setup finished! **
```

Wich version of the image are you using? I tested it with `'docker.io/bitnami/mariadb-galera:10.5-debian-10'`

**Comment by tommyalatalo** [comment]
> Hi @tommyalatalo ,
> I am not able to reproduce the issue.
> I just cloned the repository, created a custom sql file and added the volume to the docker-compose obtaining the expected output:
> 
> ```
> mariadb-galera_1  | mariadb 06:15:52.57 INFO  ==> Initializing mariadb database
> mariadb-galera_1  | mariadb 06:15:52.58 INFO  ==> Updating 'my.cnf' with custom configuration
> mariadb-galera_1  | mariadb 06:15:52.61 INFO  ==> Setting wsrep_node_name option
> mariadb-galera_1  | mariadb 06:15:52.62 INFO  ==> Setting wsrep_node_address option
> mariadb-galera_1  | mariadb 06:15:54.46 INFO  ==> Starting mariadb in background
> mariadb-galera_1  | mariadb 06:15:56.59 INFO  ==> Loading user's custom files from /docker-entrypoint-initdb.d
> mariadb-galera_1  | mariadb 06:15:56.62 INFO  ==> Stopping mariadb
> mariadb-galera_1  | mariadb 06:15:58.62 INFO  ==> ** MariaDB setup finished! **
> ```
> 
> Wich version of the image are you using? I tested it with `'docker.io/bitnami/mariadb-galera:10.5-debian-10'`

We're using bitnami/mariadb-galera:10.5.5

**Comment by miguelaeh** [comment]
Hi @tommyalatalo ,
Could you share the logs of the container please?

**Comment by lcfang** [comment]
@tommyalatalo I think `run.sh` is the true progress to setup the msriadb-galera-cluster. `setup.sh` is only initial

**Comment by miguelaeh** [comment]
Hi @lcfang ,
The setup prepares the directories, initializes MariaDB executed the init scripts and stops MariaDB again.
The run.sh will be on charge to execute MariaDB and will create the main process on the container.
You can see all the logic at https://github.com/bitnami/bitnami-docker-mariadb-galera/tree/master/10.3/debian-10/rootfs/opt/bitnami/scripts/mariadb-galera

**Comment by slyadams** [comment]
I am having a similar problem, but I'm not sure if its identical. I have a shell script inside the /docker-entrypoint-initdb.d directory. It runs fine on the bootstrap node, but not on the others when they come up, I get the same MySQL connection failure message. I noticed on those nodes that fail I don't see the `Starting mariadb in background` log message. I think I've traced this to the fact that in setup.sh there is:

~~~~
mysql_initialize
# Other stuff
mysql_custom_init_scripts
~~~~

So the `mysql_custom_init_scripts` function runs regardless of the node type. However, the `mysql_initialize` does not start Maria during the initialization unless the node is a boostrap. This means pretty much any .sql init file or .sh that accesses the database will fail on the non-bootstrap nodes, and because these scripts fail, the whole startup then fails.

**Comment by dani8art** [comment]
Hi @tommyalatalo we finally were able to reproduce the issue, it seems to be related to @slyadams suspicions. We just created an internal task to fix the issue and included it in our backlog. As the impact of the issue is limited and not critical, we can’t provide an ETA. Nevertheless, it will be considered for future application versions.

BTW, We can propose a workaround to this error by using some logical conditions in your scripts

```bash
#!/bin/sh
if [[ $MARIADB_GALERA_CLUSTER_BOOTSTRAP == "yes"  ]]; then
  echo "BOOTSTRAP node"
  mysql -P 3306 -uroot -p$MARIADB_ROOT_PASSWORD -e "SELECT 1;";
else
  echo "No BOOTSTRAP node"
fi
```

**Comment by carrodher** [comment]
Hi, we just released a new revision of the different mariadb branches. The `-r6` revision in each branch should contain some changes in order to fix this issue, for example, https://github.com/bitnami/bitnami-docker-mariadb-galera/commit/dff271f2a065c22e0139512590e73036006ede84. Basically we improved the logs and added a wait to ensure the database is up before executing the `.sql`/`.sql.gz` files.

In the same way, we added more information in the Docker image and Helm Chart READMEs.
