### ISSUE TITLE
Invalid debug check causes infinite loop - runs arbitrary commands

### ISSUE THREAD

**Issue by sbienkow** [bitnami/bitnami-docker-mariadb-galera#30]
**Description**

If `BITNAMI_DEBUG` environment variable is set to `yes`, it causes `yes` program to launch, which leads to the init process being infinitely stuck printing `y` to the console.

**Steps to reproduce the issue:**

1. Run `docker run --rm -e BITNAMI_DEBUG=yes bitnami/mariadb-galera`

**Describe the results you received:**

The screen is flooded with lines with `y` character and the database doesn't start.

**Describe the results you expected:**

Database starts successfully within a few seconds.

**Additional information you deem important (e.g. issue happens only occasionally):**

The issue is caused by invalid check over at `debug_execute` function in `libos.sh`: https://github.com/bitnami/bitnami-docker-mariadb-galera/blob/master/10.5/debian-10/prebuildfs/opt/bitnami/scripts/libos.sh#L194
Instead of checking the contents of `BITNAMI_DEBUG` it launches its content as command.

**Comment by javsalgar** [comment]
Hi,

Thank you for using Bitnami. I was able to reproduce the issue. We will work on a fix, thanks for reporting!

**Comment by fmulero** [comment]
It seems this issue was fixed long time ago.

We are also moving to [a new repository](https://github.com/bitnami/containers) in order to be aligned with the approach followed in [bitnami/charts](https://github.com/bitnami/charts). More information [here](https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html). If you are still facing this issue, please open a new issue in [bitnami/containers](https://github.com/bitnami/containers) repository
