### ISSUE TITLE
MariaDB 10.6

### ISSUE THREAD

**Issue by Taragos** [bitnami/bitnami-docker-mariadb-galera#54]
Hello,
this is more of a question than an issue.

MariaDB already released the 10.6 Version that contains quite a few features I am interested in.
My current cluster is based on your guys image (great work btw.), but I am in the need of upgrading.

Could you tell me when you will add the 10.6 Version?

**Comment by carrodher** [comment]
Hi, we are tracking new versions from this official website: https://downloads.mariadb.org/mariadb/+releases/

At this moment, the different `10.6.X` versions are not _stable_, all of them are _alpha_, _beta_, or _RC_. When a new `10.6.X` version appears marked as _stable_ it should be available as part of the Bitnami catalog.
As it is a major version we need to create a new branch, this process is manual since we need to adapt our internal test & release pipeline, not like a new version inside an existing branch that is released in an automated way, so some delay is expected once the new version is released in the upstream project. But we have some automated tools tracking the above URL looking for new _stable_ versions
